# Generated by Django 5.1 on 2024-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accommodation_agency_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/agency/'),
        ),
    ]
