# Generated by Django 5.1 on 2024-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/accommodations/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
    ]
