# Generated by Django 5.1 on 2024-09-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accommodation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agency',
        ),
    ]
