# Generated by Django 5.0.6 on 2024-09-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_booking_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type_of_accommodation',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('villa', 'Villa')], max_length=20),
        ),
    ]
