# Generated by Django 5.0.6 on 2024-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accommodation_type_of_accommodation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
