# Generated by Django 5.0.6 on 2024-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/agency/')),
                ('simple_price', models.CharField(max_length=255)),
                ('classic_price', models.CharField(max_length=255)),
                ('vip_price', models.CharField(max_length=255)),
            ],
        ),
    ]
