# Generated by Django 5.0.6 on 2024-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='classic_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='simple_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
