# Generated by Django 5.1 on 2024-09-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='accommodation_ptr',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
